import '../styles/globals.scss';
import type {Metadata} from 'next';
import {roboto} from "@/fonts/fonts";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <main className="main container">
            {children}
        </main>
        </body>
        </html>
    )
}
